name: Deploy RADICAL-Tutorials container
on:
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  deploy:
    name: Push docker image
    runs-on: ubuntu-latest
    env:
      TUTORIAL_TAG: radicalcybertools/tutorials:latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
    - uses: docker/build-push-action@v6
      with:
        context: ./src/
        file: ./docker/Dockerfile
        build-args: |
          TUTORIAL_NAME=latest
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ env.TUTORIAL_TAG }}

